[package]
name = "organizeit2_py"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "organizeit2"
path = "rust/python/lib.rs"
crate-type = ["cdylib"]

[dependencies]
organizeit2 = { path = "./rust", version = "*" }
<<<<<<< before updating
pyo3 = { version = "0.28.2", features = ["abi3-py39", "extension-module", "multiple-pymethods"] }
=======
pyo3 = { version = "0.28.2", features = ["abi3", "extension-module", "multiple-pymethods"] }
>>>>>>> after updating

[profile.release]
panic = 'abort'
lto = true
